sudo: false
language: node_js
node_js:
  - 8

script:
  - yarn install

branches:
  only:
    - master # Used for publishing releases automatically
    - develop

before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
       git clone "https://github.com/$TRAVIS_REPO_SLUG.git" "$TRAVIS_REPO_SLUG";
       cd "$TRAVIS_REPO_SLUG";
       git checkout -qf "$TRAVIS_COMMIT";
    fi

before_deploy:
  - git config --global user.name TravisCI
  - git config --global user.email travis@travis-ci.org
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - git checkout master
  - npm run automatic-release # Here happens the magic

deploy:
  provider: npm
  email: qtuzov@gmail.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    repo: kisenka/generator-kisenka